import type { Metadata } from "next"
import { Merriweather_Sans } from "next/font/google"
import "./globals.css"
import Navbar from "./components/Navbar"
import CartProvider from "./components/Providers"
import ShoppingCartModal from "./components/ShoppingCartModal"

const Merriweather = Merriweather_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={Merriweather.className}>
        <CartProvider>
          <Navbar />
          <ShoppingCartModal />
          {children}
        </CartProvider>
      </body>
    </html>
  )
}
